### ISSUE TITLE
Compile to ES5 before publish

### ISSUE THREAD

**Issue by KyleGobel** [RikkiGibson/isomorphic-xml2js#4]
Hey Rikki,

I see this is a dependency to ms-rest-js.

I'm using create-react-app in a typescript project, and when this is pulled in it's failing during the minify step.

![image](https://user-images.githubusercontent.com/4460054/41052845-f6367154-6987-11e8-9bf7-75c76c6834b8.png)

I see that this is targeting es 2017 and that's fine, but certain commonly used tools (create-react-app) can't deal with it and just cause things to break.

What are thoughts on compiling this here before publishing?

**Comment by RikkiGibson** [comment]
Thanks for the heads up about this. It looks like create-react-app not compiling the dependencies is a known problem that is solved in `react-scripts@next`.

https://github.com/facebook/create-react-app/issues/3815

If you're feeling bold you can try it now. I reproduced the issue you described and was able to fix it by upgrading the react-scripts dependency: 

```sh
$ # Create a new application
$ npx create-react-app@next --scripts-version=2.0.0-next.66cc7a90
$ # Upgrade an existing application
$ yarn upgrade react-scripts@2.0.0-next.66cc7a90
```

I understand that it's not necessarily reasonable to have to upgrade to a prerelease tool, so I'll look into publishing a version of this package which targets the earlier ES version.

**Comment by KyleGobel** [comment]
Yeah i saw that it was coming in 2.0.  I can't so easily upgrade though because I use react-scripts-ts (the typescript version) which lags a bit behind the proper create-react-app.  I believe they're working on the 2.0.0 merge though,  I'll have to check into that.

**Comment by RikkiGibson** [comment]
`isomorphic-xml2js@0.1.3` now targets ES5. It seems to solve the problem you're describing. Let me know if it works for you.

**Comment by KyleGobel** [comment]
Yep that fixes it for me.  Thanks a lot!
